version: '3.5'

services:
  postgresDB:
    image: postgres
    restart: always
    container_name: container_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./sql:/var/lib/postgresql/data
    ports:
      - '5432:${POSTGRES_PORT}'
    networks:
      - postgresDB

networks:
  postgresDB:
    driver: bridge
