version: "3.3"

services:
  app:
    build: .
    volumes:
      - './:/app'
    image: app
    networks:
      - default
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 20s
        window: 120s
    restart: unless-stopped
    ports:
      - '4000:3000'
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
  db:
    image: postgres
    restart: unless-stopped
    container_name: container_postgres
    deploy:
      resources:
        limits:
          cpus: "0.75"
        reservations:
          cpus: "0.25"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - sql:/var/lib/postgresql/data
    ports:
      - '5432:${POSTGRES_PORT}'

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8090:8080
volumes:
  postgresDB:
